### Para obtener los productos
GET http://localhost:3000/productos
Content-Type: application/json

###Consulta de producto
GET http://localhost:3000/productos/9
Content-Type: application/json

###Crear Producto
POST http://localhost:3000/productos
Content-Type: application/json

{
  "nombre": "Laptop",
  "precio": 599.9,
  "descripcion": "Laptop moderna con 8GB RAM y 256GB SSD",
  "disponible": true,
  "fecha_ingreso": "2025-07-06T14:00:00.000Z",
  "categoriaId": 2
}

###Actualizar un producto
PUT http://localhost:3000/productos/3
Content-Type: application/json

{
  "nombre": "Laptop Dell",
  "precio": 599.99,
  "descripcion": "Laptop moderna con 8GB RAM y 256GB SSD",
  "disponible": true,
  "fecha_ingreso": "2025-07-06T14:00:00.000Z",
  "categoriaId": 2
}

###Eliminar un producto
DELETE http://localhost:3000/productos/8
Content-Type: application/json

###Obtener productos disponibles
GET http://localhost:3000/productos/disponibles?disponible=true
Content-Type: application/json